name: Auto Label Issues

on:
  issues:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label to new issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: needs-triage
